### ISSUE TITLE
Pushing new releases to registry.connect.redhat.com/bitnami/fluent-bit

### ISSUE THREAD

**Issue by ombre8** [bitnami/bitnami-docker-fluent-bit#3]
Hi there,

we are using fluentbit on our Openshift. Due to Company Policies we are only allowed to Pull images from local and Red Hat registries. Are you planing to push new releases to registry.connect.redhat.com? That would be fabulous.

Thanks in advance

Lukas

**Comment by ombre8** [comment]
I just had a closer look, seems like, the rhelbased image didn't get an update... Are there any plans to update this as well?

**Comment by carrodher** [comment]
Hi, we currently do not have a partnership with Red Hat for Bitnami, unfortunately, these images do not receive updates since it expired and will not be updated in the short/medium term

**Comment by ombre8** [comment]
Hi @carrodher 
thanks for your answer
